Class TPANNUAIRE.Operation.CrudPerson Extends Ens.BusinessOperation
{

Method GetAll(pRequest As TPANNUAIRE.Messages.Operation.GetAllRequest, Output pResponse As TPANNUAIRE.Messages.Operation.GetAllResponse) As %Status
{
}

Method GetById(pRequest As TPANNUAIRE.Messages.Operation.GetByIdRequest, Output pResponse As TPANNUAIRE.Messages.Operation.GetByIdResponse) As %Status
{
}

Method CreatePerson(pRequest As TPANNUAIRE.Messages.Operation.CreatePersonRequest, Output pResponse As TPANNUAIRE.Messages.Operation.CreatePersonResponse) As %Status
{
}

Method UpdateById(pRequest As TPANNUAIRE.Messages.Operation.UpdateByIdRequest, Output pResponse As TPANNUAIRE.Messages.Operation.UpdateByIdResponse) As %Status
{
}

Method DeleteById(pRequest As TPANNUAIRE.Messages.Operation.DeleteByIdRequest, Output pResponse As TPANNUAIRE.Messages.Operation.DeleteByIdResponse) As %Status
{
}

Method SearchByCriteria(pRequest As TPANNUAIRE.Messages.Operation.SearchByCriteriaRequest, Output pResponse As TPANNUAIRE.Messages.Operation.SearchByCriteriaResponse) As %Status
{
}

}
