Class TPANNUAIRE.Messages.Operation.CreatePersonRequest Extends TPANNUAIRE.Messages.Basic.BasicRequest
{

Property Person As TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="CreatePersonRequestDefaultData">
<Subscript>"CreatePersonRequest"</Subscript>
<Value name="1">
<Value>Person</Value>
</Value>
</Data>
<DefaultData>CreatePersonRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
