Class TPANNUAIRE.Messages.Operation.GetByIdResponse Extends TPANNUAIRE.Messages.Basic.BasicResponse
{

Property Person As TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="GetByIdResponseDefaultData">
<Subscript>"GetByIdResponse"</Subscript>
<Value name="1">
<Value>Person</Value>
</Value>
</Data>
<DefaultData>GetByIdResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
