Class TPANNUAIRE.Messages.Operation.SearchByCriteriaRequest Extends TPANNUAIRE.Messages.Basic.BasicRequest
{

Property Person As TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="SearchByCriteriaRequestDefaultData">
<Subscript>"SearchByCriteriaRequest"</Subscript>
<Value name="1">
<Value>Person</Value>
</Value>
</Data>
<DefaultData>SearchByCriteriaRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
