Class TPANNUAIRE.Messages.Operation.SearchByCriteriaResponse Extends TPANNUAIRE.Messages.Basic.BasicResponse
{

Property ListPerson As list Of TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="SearchByCriteriaResponseDefaultData">
<Subscript>"SearchByCriteriaResponse"</Subscript>
<Value name="1">
<Value>ListPerson</Value>
</Value>
</Data>
<DefaultData>SearchByCriteriaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
