Class TPANNUAIRE.Messages.Operation.UpdateByIdResponse Extends TPANNUAIRE.Messages.Basic.BasicResponse
{

Property Person As TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="UpdateByIdResponseDefaultData">
<Subscript>"UpdateByIdResponse"</Subscript>
<Value name="1">
<Value>Person</Value>
</Value>
</Data>
<DefaultData>UpdateByIdResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
