Class TPANNUAIRE.Messages.Operation.UpdateByIdRequest Extends TPANNUAIRE.Messages.Basic.BasicRequest
{

Property Person As TPANNUAIRE.WebObject.WPerson;

Storage Default
{
<Data name="UpdateByIdRequestDefaultData">
<Subscript>"UpdateByIdRequest"</Subscript>
<Value name="1">
<Value>Person</Value>
</Value>
</Data>
<DefaultData>UpdateByIdRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
